### ISSUE TITLE
Calculate homography is empty

### ISSUE THREAD

**Issue by alex-makarov** [NVIDIA-AI-IOT/deep_nav_layers#1]
Hey Rachel,

I'm trying to build the costmap from image segmentation, and noticed that the link on homography calibration -- https://github.com/NVIDIA-AI-IOT/deep_nav_layers/wiki/Calibrating-a-Camera - is empty. Do you have this information somewhere? Thanks!

Alex

**Comment by rachel-1** [comment]
Thanks for your interest in the project! I should warn you that the repo may not be officially maintained anymore, given that it was from my intern project a few years back. I'm still happy to help though.

In terms of homography calibration, you can use [calculate_homography.cpp](https://github.com/NVIDIA-AI-IOT/deep_nav_layers/blob/master/calibrate_homography/calculate_homography.cpp) to do that for you. Just edit [calibration_points.yml](https://github.com/NVIDIA-AI-IOT/deep_nav_layers/blob/master/calibrate_homography/calibration_points.yml) to change the points for your use case.

To get the points, I set up my bot, then taped out squares in front of it. Most people will print a checkerboard pattern, but I just used a meter stick and sticky notes because I wanted a pretty large pattern. I then took a picture with the camera and used the display software to mouse over key points in my pattern and record those pixel coordinates. Again, some people will use computer vision to do this automatically, but I didn't want to add complexity.

Let me know how it goes for you and I can update the wiki.

**Comment by alex-makarov** [comment]
Hey @rachel-1, thank you for the detailed answer!
JFYI, I've managed to get the homography using computer vision approach from this repo -- https://github.com/tum-phoenix/drive_ros_camera_homography  -- seems to work fairly well.
